# words for hangman game

words =  ("apple",
          "orange",
          "cherry",
          "banana",
          "coconut",
          "pineapple",
          "brain",
          "car",
          "bread",
          "toy",
          "factory",
          "store",
          "pizza",
          "couch",
          "painting",
          "book",
          "television",
          "monitor",
          "light",
          "lamp",
          "book",
          "mouse",
          "bake",
          "dragon",
          "sword",
          "person",
          "bank",
          "exam",
          "computer",
          "soup",
          "cat",
          "dog",
          "water",
          "fire",
          "air",
          "earth",
          "nation",
          "soccer",
          "tennis",
          "volleyball",
          "sunflower",
          "frog",
          "tiger",
          "puma",
          "grass",
          "keyboard")


